
// Post
export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'

// Posts
export const POSTS_IMPORTED = 'POSTS_IMPORTED'
export const SORT_POSTS = 'SORT_POSTS'
export const GET_POSTS = 'GET_POSTS'

// Votes
export const UPVOTE_SINGLE_POST = 'UPVOTE_SINGLE_POST'
export const DOWNVOTE_SINGLE_POST = 'DOWNVOTE_SINGLE_POST'
export const UPVOTE_SINGLE_COMMENT = 'UPVOTE_SINGLE_COMMENT'
export const DOWNVOTE_SINGLE_COMMENT = 'DOWNVOTE_SINGLE_COMMENT'
export const UPVOTE_POST_IN_LIST = 'UPVOTE_POST_IN_LIST'
export const DOWNVOTE_POST_IN_LIST = 'DOWNVOTE_POST_IN_LIST'

// Comments
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const GET_COMMENTS = 'GET_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const COMMENT_EDITTED = 'COMMENT_EDITTED'


// Categories
export const GET_CATEGORIES = 'GET_CATEGORIES'